name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - arthking17-patch-1

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_IMAGE: ""
  DOCKER_TAG: ""

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set outputs
      id: vars
      run: echo "image_name=$(echo ${GITHUB_REPOSITORY} | cut -d '/' -f 2)" >> $DOCKER_IMAGE && echo "docker_tag=$(echo ${GITHUB_REF} | cut -d '/' -f 3)-$(echo "$GITHUB_SHA" | cut -c-4)" >> $DOCKER_TAG

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ steps.vars.outputs.sha_short }}"
      env:
        DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
        DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
        DOCKER_TAG: ${{ env.DOCKER_TAG }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
