name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - arthking17-patch-1

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_IMAGE: weather-app
  DOCKER_TAG: "$(echo ${{ github.ref }}-${{ github.sha }} | sed -e 's/[^a-z0-9._-]/-/g')"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: "${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"
      env:
        DOCKER_REGISTRY: ${{ env.DOCKER_REGISTRY }}
        DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
        DOCKER_TAG: ${{ env.DOCKER_TAG }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
